CRA7C/SSD

ssd/nand_driver.py
ssd/result_manager.py
ssd/ssd.py
tests/ssd/test_nand_driver.py
tests/ssd/test_result_manager.py
tests/ssd/test_ssd.py

* SSD read/write 기능 구현
* NandDriver를 통해서 nand에 저장된 데이터 접근하여 read/write 수행
* ResultManager를 통해서 읽기 기능 결과를 출력
* 가상의 nand에 해당하는 nand.txt 파일을 다루는 클래스
* 출력 결과를 전달하기위한 result.txt 파일을 다루는 클래스

[add] SSD read/write 기능 구현

---

testapp/testshell.py
tests/testapp/test_testshell.py

test shell application 관련 구조 및 TCs 작성하였습니다.

[FEAT] TCs for Feature/test shell application

---

testapp/command/fullread.py
testapp/command/read.py
tests/testapp/test_command_fullread.py
tests/testapp/test_command_read.py

1. read/fullread 기능구현 입니다.
2. 테스트 코드 추가 했습니다.

app read fullread 기능 추가 건

---

testapp/test_shell.py
testapp/testshell.py
tests/testapp/test_testshell.py

1. 입력 파라미터 유효성 검사 및 타입 변환
2. 테스트 코드 subtests 추가하여 정리

[FEAT] check valid parameters 

---

ssd/__main__.py
ssd/common.py
ssd/nand_driver.py
ssd/ssd.py
tests/ssd/test_main.py
tests/ssd/test_ssd.py

* 데이터를 읽고 쓰기 위한 사용자 인터페이스
* command 해석 후, 적절한 동작 수행
* command 유효성 검사 기능(추가 예정)
* 공통으로 사용하는 기능을 common 모듈로 따로 작성

[mod] ssd 읽기/쓰기 기능을 위한 통합 테스트 추가 및 기능 구현

---

testapp/test_app2.py
tests/testapp/test_test_app2.py

- test_app2.py, test_test_app2.py 추가.

TestApp2 Script 추가.

---

testapp/testshell.py
tests/testapp_test/test_testshell.py

testapp1 and testapp2 관련 TC 추가 및 
이전 리뷰 REFACTOR 제안 반영 수행했습니다

[FEAT] TC for testapp

---

testapp/__main__.py
testapp/testshell.py

__main__.py 파일 추가
및 마이너 리팩토링 하였습니다

[FEAT] add __main__.py

---

testapp/ssd_driver.py
testapp/util.py
tests/testapp_test/test_ssd_driver.py

#25 
- SsdDriver 생성할 떄 마다 result.txt파일 유무 확인하여 없으면 생성함. 
- util에 get_ssd_result_file_path로 result.txt파일 주소를 가져옴. 
- SsdDriver에서 subprocess 실행 할 때 -m 옵션 붙이도록 수정  --> test_도 수정.

[Feature/command] #25

---

ssd/__main__.py

ISSUE https://github.com/CRA7C/SSD/issues/25 해결하기 위해 project root를 추가하였습니다

[FIX] add project root

---

testapp/util.py

- ssd value 가 0xFFFFFFFF 까지 가능한 것으로 수정
- 해당 파일 상수 적용

[FIX] range of ssd value

---

testapp/test_app2.py
tests/testapp_test/test_command_fullread.py
tests/testapp_test/test_command_read.py
tests/testapp_test/test_test_app1.py
tests/testapp_test/test_test_app2.py
utils/util_log.py

1. 함수명과 변수명이 같아 함수명 수정했습니다.
2. test 코드 함수명이 잘못되어 있어 수정했습니다. 
3. 함수 호출 전 함수명 호출하는 decorator 추가해놨습니다.

함수명 변경 및 함수명 출력하는 decorator 추가

---

ssd/__main__.py
ssd/common.py

[REFACTOR] validation of hex value

---

tests/testapp_test/test_command_parser.py
tests/testapp_test/test_testshell.py

반드시 남겨야 하는 정보 제외하고 print 구문 삭제

[mod] 테스트 코드에 있는 print 구문 삭제

---

tests/testapp_test/test_testshell.py

Conflict merge 오류

---

ssd/__main__.py
ssd/nand_driver.py
ssd/solidstatedrive.py
tests/ssd_test/test_main.py
tests/ssd_test/test_nand_driver.py
tests/ssd_test/test_ssd.py

SSD 내 erase 기능 및 관련 TC 추가 하였습니다

[FEAT] Erase in SSD

---

testapp/command/erase.py
testapp/ssd_driver.py
tests/testapp_test/test_command_erase.py

* SsdDriver 클래스를 사용하여 erase를 수행합니다.
* 전달 받은 size가 10보다 클 경우,  10 단위로 나눠서 loop를 돌며 명령을 처리합니다.
* 전달 받은 <시작 LBA> + <삭제할 size>가 LBA 범위를 넘어설 경우, 시작 LBA부터 마지막 LBA인 99까지 모든 데이터를 삭제합니다.

[add] erase command 추가

---

testapp/scripts/__init__.py
testapp/scripts/_script_manager.py
testapp/scripts/full_read10_and_compare.py
testapp/scripts/full_write_read_compare.py
testapp/scripts/loop_write_and_read_compare.py
testapp/scripts/test_app1.py
testapp/scripts/test_app2.py
testapp/scripts/write10_and_compare.py
testapp/ssd_driver.py

- scripts 폴더 내 개별 .py 파일들은 개별 test script 로 간주하며 개별 실행 가능함. 
- 각각을 application 으로 간주하고 `_script_manager` 에서는 이를 subprocess 로 동작시키는 방식
- 실제 `get_test_scripts` 할 때마다 test script 리스트를 받아오니, runtime 중에 테스트 스크립트 추가되어도 대응 가능함. 
- testshell 쪽에 script 기반으로 사용하도록 변경해야함. 현재의 testshell 개발자와의 조율 필요.

[feat] Runner 개발을 위한 `testapp.scripts` 모듈 구현 완료. 

---

testapp/command/erase.py
testapp/command/erase_common.py
testapp/command/erase_range.py
tests/testapp_test/test_command_erase_range.py
tests/testapp_test/test_erase_range.py

* erase 커맨드와 유사한 부분이 많아 공통 부분을 erase_common 모듈로 따로 뺐습니다.

[add] erase_range 커맨드 추가

---

utils/util_log.py

logger class 구현 입니다.
1. latest.log 에 저장하는거만 구현 되었습니다.
2. console에는 INFO 레벨로 나오고, 파일에는 DEBUG레벨로 출력됩니다.
[출력예시]
[24.07.17 14:27] LogTest.another_function()             : hihi
[24.07.17 14:27] LogTest.another_function()             : hoho
[24.07.17 14:31] LogTest.another_function()             : hihi
[24.07.17 14:31] LogTest.another_function()             : hoho

[FEAT] Logger class 구현

---

testapp/command/__init__.py
testapp/command_parser.py
tests/testapp_test/test_command_parser.py

conflict 최소화를 위해 erase 명령어 유효성 확인 기능 먼저 PR 생성합니다.

[mod] erase 명령어 실행할 수 있도록 command parser에 erase command 추가

---

utils/util_log.py

1. latest.log가 10kb넘으면 until_날짜_시간.log로 변경합니다.
ex) until_240717_160049.log 
※ ppt예시에서 17h_12m_11s 에서 h m s는 제외했어요. 
2. Logger()를 직접 사용할 때, 추가로 핸들러가 생성되어 여러번 출력되는 문제가 있어 수정했습니다.
3. self.is_already_bkup_file()는 구현 전 입니다.

Logger기능2 : 로그 기록 규칙 추가

---

testapp/__main__.py
testapp/command_parser.py
testapp/constants.py
testapp/scripts/__init__.py
testapp/scripts/_script_manager.py
testapp/scripts/dummy_test.py
testapp/scripts/full_read10_and_compare.py
testapp/scripts/full_write_read_compare.py
testapp/scripts/loop_write_and_read_compare.py
testapp/scripts/test_app1.py
testapp/scripts/test_app2.py
testapp/scripts/write10_and_compare.py
testapp/testshell.py
testapp/util.py
tests/testapp_test/test_command_parser.py
tests/testapp_test/test_testshell.py
utils/util_log.py

변경 내용 
- test shell 에서 test script 의 ID (클래스의 이름) 을 실행하면 동작
- test shell 에서 명령어 입력할때마다 scripts 폴더의 .py 파일들 리스트 업
- test shell 동작 중에 test script 추가 시 정상 동작 확인 완료.
- test script 들을 test shell app. 과 별개의 process 에서 동작해야 요구사항 만족
- Runner 구현을 처음부터 재빌드 이슈가 발생하지 않도록 구현함.

Runner 구현 및 재빌드 이슈 문제 해결 완료.

---

my_logger/util_log.py

until.log 형식은 하나의 파일만 있도록 until.log 만들기 전 until.log -> until.zip으로 변경합니다.
그런일은 없겠지만, 한번에 10kb(과제에서 정한)넘는 로그가 찍힐 때 파일 rename 문제가 있어 파일이 있으면 지우는 로직도 넣어놨습니다.

Logging 기능 2 - until.log를 until.zip으로 변경

---

ssd/__main__.py
ssd/command_buffer.py

- Command Buffer에서 Push / Flush 타이밍이 잘못되어있어 수정했습니다.

[Bugfix - Command Buffer] 10만 버퍼링해야하는데 11개를 버퍼링하고 있었음.  해당 내용 수정

---

ssd/__main__.py

ssd.__main__ SSDRunner.is_valid_command에 Flush 명령어 처리 추가.

[Feature - Flush] ssd flush 추가.

---

testapp/command/read.py

**read 커맨드는 화면에 결과를 출력해야합니다.**
* 결과를 리턴하고 그대로 종료
* 결과를 화면에 출력

[hotfix] read 커맨드 버그 수정

---

ssd/__main__.py
ssd/command.py
ssd/command_buffer.py
ssd/common.py
ssd/result_manager.py
ssd/solidstatedrive.py
testapp/ssd_driver.py

[REFACTOR] ssd 실행 코드 관련 리팩토링

---

testapp/command/fullread.py
testapp/testshell.py

read와 같은 문제로 fullread command 수정합니다.
#70

[hotfix] fullread 화면 출력 안되는 문제 수정

---

ssd/__main__.py
ssd/command.py
ssd/command_buffer.py
ssd/common.py
tests/ssd_test/test_command_buffer.py
tests/ssd_test/test_main.py

[Refactoring] SSDRunner, CommandBuffer 
SSDRunner의 is_valid_command함수를 
Command별 validate_command 로 이동

[Refactoring] SSDRunner, CommandBuffer 

---

ssd/__main__.py
testapp/command/fullwrite.py
testapp/command/read.py
testapp/command/write.py
testapp/command_parser.py
testapp/scripts/dummy_test.py
testapp/scripts/full_read10_and_compare.py
testapp/scripts/full_write_read_compare.py
testapp/scripts/loop_write_and_read_compare.py
testapp/scripts/test_app1.py
testapp/scripts/test_app2.py
testapp/scripts/write10_and_compare.py
testapp/ssd_driver.py
testapp/util.py

testapp module type hint 추가하였습니다

[REFACTOR] testapp module type hint 추가

---

my_logger/util_log.py
testapp/command/fullread.py
testapp/command/help.py
testapp/command/read.py
testapp/command_parser.py
testapp/scripts/_script_manager.py
testapp/testshell.py

logger 통한 출력으로 변경하는 수정입니다.
1. console/파일 출력은 Logger().info()로 출력합니다. (console level : logging.INFO / info 이상 레벨만 console로 출력됨, file level : logging.DEBUG / 가장 낮은 레벨)
2. 파일에만 반영해야 하는 출력은 Logger().debug()로 출력합니다. 
3. script쪽은 시나리오 확인해서 다시한번 확인이 필요합니다.
4. 앞선 PR들 머지 후 rebase한 후 재PR할게요.

print로 출력하는 부분 logger 통한 출력으로 변경

---

my_logger/util_log.py
testapp/command/command_factory.py
testapp/scripts/_script_manager.py
testapp/testshell.py

1. function 이름을 기준으로 패딩하다보니, class.function  ':' 위치가 왔다갔다하는 문제가 있음.
class.function 을 기준으로 패딩하는 것으로 코드 수정함
2. 이전 PR시 생성자 여러번 사용하는 경우, 전역객체 생성해서 사용하자는 의견이 있어 반영함

logger : 위치 변경과 logger 객체 추가 건

---

ssd/command.py

- shell 에서 'read -0' 실행 시 오류 발생 해결하였습니다

[HOTFIX] SSD R -0 실행 오류 수정

---

testapp/command/fullread.py
testapp/scripts/_script_manager.py
testapp/scripts/full_read10_and_compare.py
testapp/scripts/full_read_compare.py
testapp/scripts/full_write_read_compare.py
testapp/scripts/loop_write_and_read_compare.py
testapp/scripts/test_app1.py
testapp/scripts/test_app2.py
testapp/scripts/write10_and_compare.py
testapp/scripts/write_and_erase.py
testapp/testshell.py

- "python -m testapp run_list.lst" 조건에서는 print 미출력 
- "shell " 조건에서는 print 출력 
하도록 개선

[hotfix] test script 들을 shell 에서 동작시 콘솔 출력 미지원 문제 해결

---

ssd/__main__.py
testapp/command/command_factory.py
testapp/scripts/_script_manager.py
testapp/testshell.py

객체생성해서 사용하면 공유자원 문제가 있어, 생성자() 사용하도록 revert했습니다.
동작 확인 부탁드립니다.

[FIX] 공유파일 접근 문제로 logger 객체사용 revert

---

testapp/command/command_factory.py
testapp/command/erase.py
testapp/command/erase_range.py
testapp/command/fullwrite.py
testapp/command/read.py
testapp/command/write.py
testapp/testshell.py
testapp/util.py
tests/testapp_test/test_command_parser.py

* 예외 메세지 세분화
* 최상단에 try-catch 구문 사용하여 사용자에게 에러 메세지 출력되도록 변경
---

[refactor] exception handling 변경

---

testapp/command/erase_range.py
tests/testapp_test/test_command_erase_range.py

- erase_range의 is_valid_args에서 lba range check하는 부분에서 is_in_range_lba(end_lba)에 end_lba-1가 들어가도록 수정

[bugfix] erase_range에서 99번 데이터 못 지우는 현상 개선

---

testapp/testshell.py

DummyFailTest 시 INVALID COMMAND 출력되는 문제 개선

DummyFailTest 시 INVALID COMMAND 출력되는 문제 개선
